### ISSUE TITLE
object of type 'int' has no len()

### ISSUE THREAD

**Issue by cwnuyangyan** [encounter1997/SFA#1]
I run this demo, but face a error in the line of 673 of deformable_detr.py, 
`domain_levels += len(args.hda)`
args.hda is int, so Exception has occurred: TypeError object of type 'int' has no len()

**Comment by encounter1997** [comment]
https://github.com/encounter1997/SFA/blob/3a0725f6dde33b10d6fc471c079973a9e6f10c52/main_da.py#L102
With `nargs='+'`, `args.hda` should be a list if it's not `None`. 

Please provide more details about your running command, so I can better understand your issue.

**Comment by encounter1997** [comment]
https://github.com/encounter1997/SFA/blob/3a0725f6dde33b10d6fc471c079973a9e6f10c52/main_da.py#L102
With `nargs='+'`, `args.hda` should be a list if it's not `None`. 

Please provide more details about your running command, so I can better understand your issue.

**Comment by encounter1997** [comment]
https://github.com/encounter1997/SFA/blob/3a0725f6dde33b10d6fc471c079973a9e6f10c52/main_da.py#L102
With `nargs='+'`, `args.hda` should be a list if it's not `None`. 

Please provide more details about your running command, so I can better understand your issue.

**Comment by encounter1997** [comment]
I will close this issue if you don't have any further questions.
