### ISSUE TITLE
Question about the Paper

### ISSUE THREAD

**Issue by michaelku1** [encounter1997/SFA#12]
Hello, Thanks for your amazing work. I have a question about the paper where it explains why a consistency loss is used for constraining the decoder output predictions. It is mentioned in the paper that 

_"Since no semantic label is available on the target domain, the object detector is prone to produce inaccurate matches between object queries and ground truth objects on the target domain."_ 

I don't quite I understand what it means by that. Since you don't have any labels for target data, how is it possible to do matching when you actually don't have the ground truths? Thanks.

**Comment by michaelku1** [comment]
In that case, is it possible that you are trying to say matches on the "source domain" instead of on the "target domain"? The motivation behind using consistency loss to constrain the decoder output predictions seems reasonable, but I am just confused about the part "object detector is prone to produce inaccurate matches between object queries and ground truth objects on the target domain."

**Comment by encounter1997** [comment]
Hi, thanks for your interest. 

The ideal model prediction should match the ground truth label. On the target domain, the object detector is prone to produce inaccurate predictions and thus leading to inaccurate matches between object queries and ground truth objects on the target domain.

We regulate the class and box prediction of individual decoder layers to be consistent. In this way, the model produces consistent matching with the ground truth in an indirect way, though the ground truth is not available.

From another perspective, we ensemble the predictions of individual decoder layers to obtain a pseudo label to supervise the training on the target domain, to achieve better performance.

**Comment by michaelku1** [comment]
This makes a lot more sense now. I thought by "matching" the paper means the "bipartite assignment" between two output predictions and ground truths. Thanks for clearing my confusion.

**Comment by michaelku1** [comment]
I think I understand it now. Thanks for clearing my confusion.
