### ISSUE TITLE
Implementation of Consistency Loss

### ISSUE THREAD

**Issue by michaelku1** [encounter1997/SFA#13]
Hello, so I noticed that there is a slight difference between the paper's fornulation of consistency loss and the actual implementation. Please correct me if I am wrong. As can be seen, the actual formulation are as follows:

![擷取1](https://user-images.githubusercontent.com/48415065/178568627-52b3ee56-3677-4fcb-909d-6cded22eb22b.PNG)

![擷取](https://user-images.githubusercontent.com/48415065/178568672-0077844b-8248-4365-996d-876c71235844.PNG)

However, I noticed that for the final consistency loss, the actual implementation uses a sum instead of an average across layers as indicated in equation 12 (weight_dict for this type of loss is 1 by defualt, therefore notion of average is perhaps not incorporated). As for the per layer consistency loss, the actual implementation uses an average over all M object queries instead of just the sum, as indicated in equation 13.

![擷取](https://user-images.githubusercontent.com/48415065/178570663-fe8c93a4-70d9-4609-964a-88057a6591ec.PNG)

 
![擷取1](https://user-images.githubusercontent.com/48415065/178570648-23ad0d02-872e-46e1-b31d-74919c3df97b.PNG)

I am wondering what are the right formulations to follow? Thanks.

**Comment by encounter1997** [comment]
Hi, as shown in Eq. 12, the loss is divided by the number of decoder layers, which equals ```len(pred_boxes_all)```. 

As for the summation in Eq. 13, we are sorry for the mistake, it should be an average over ```M``` predictions in an individual decoder layer.

**Comment by encounter1997** [comment]
Thanks for pointing it out, we will correct it and upload a new file to Arxiv.

**Comment by michaelku1** [comment]
Thanks for your reply. For equation 12,  it shows that it is normalised over number of decoder layers, but I think `len(pred_boxes_all)` gives the number of object queries `(batch_size*300)`, which is suggested here:

<img width="722" alt="截圖 2022-07-13 下午1 49 02" src="https://user-images.githubusercontent.com/48415065/178660145-7580fc6c-970b-49b8-9eca-dd271722aa1e.png">

**Comment by encounter1997** [comment]
Each element in the **list** ```pred_boxes_all``` has a shape of ```(B*300, 4)```. Afterward, they are stacked into a **tensor** with a shape of ```(num_layers, B*300, 4)```, as shown in [this line](https://github.com/encounter1997/SFA/blob/3a0725f6dde33b10d6fc471c079973a9e6f10c52/models/deformable_detr.py#L304).

**Comment by michaelku1** [comment]
I think you are right. Sorry I have not run the code yet myself so was just reading along. Thanks.
