### ISSUE TITLE
用SFA训练自己的数据集结果比deformable DETR差

### ISSUE THREAD

**Issue by sysuzgg** [encounter1997/SFA#16]
我的源域、目标域都是自己的数据集，没有修改SFA的任何参数，也没有修改官方deformable DETR的参数，SFA训练的结果比deformable DETR source-only的结果差，不知道什么原因，可否指教一下

**Comment by Bradly-s** [comment]
请问SFA训练的时候要加载deformable DETR source-only训练的权重吗？还是只用下面的命令就可以：
python main_da.py --hda 1 --cmt
