### ISSUE TITLE
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

### ISSUE THREAD

**Issue by cwnuyangyan** [encounter1997/SFA#3]
Thanks for amazing work.
 i have a problem when i run the demo in task of sim2city, assert (boxes1[:, 2:] >= boxes1[:, :2]).all() happened in function generalized_box_iou
After reading the code i find that boxes1 is the predictd bbox from a MLP layer, which i think the above assertion may happen during early training time, and then break the training.

`assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
    assert (boxes2[:, 2:] >= boxes2[:, :2]).all()`
The error info:
`assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
RuntimeError: CUDA error: device-side assert triggered
`

**Comment by encounter1997** [comment]
Hi,

Thanks for your interest in our work. The mentioned issue may be triggered by the difference in VOC and COCO annotations formats. Specifically, the coordinates are 1-indexed in VOC annotations while 0-indexed in COCO. Our annotation files are generated using the public code available at https://github.com/yukkyo/voc2coco.

**Comment by cwnuyangyan** [comment]
> Hi,
> 
> Thanks for your interest in our work. The mentioned issue may be triggered by the difference in VOC and COCO annotations formats. Specifically, the coordinates are 1-indexed in VOC annotations while 0-indexed in COCO. Our annotation files are generated using the public code available at https://github.com/yukkyo/voc2coco.

Thanks for your reply, i have solved this problem with the annotation code you provided.
