### ISSUE TITLE
Hello. Thank you for the repository. Can I use only one GPU please? 

### ISSUE THREAD

**Issue by tilahun12** [encounter1997/SFA#7]

**Comment by encounter1997** [comment]
Hi, thank you for your interest. A batch size of 4 is required to train our SFA. 
If the GPU memory can hold a batch size of 4, training with one GPU should be OK.

**Comment by Bradly-s** [comment]
> Hi, thank you for your interest. A batch size of 4 is required to train our SFA. If the GPU memory can hold a batch size of 4, training with one GPU should be OK.

The batch size must be 4? What about 2?
