### ISSUE TITLE
Why is the class number for bdd100k 9 ?

### ISSUE THREAD

**Issue by kinredon** [encounter1997/SFA#9]
Why is the class number for bdd100k 9? which is the same as cityscape to foggy cityscape. In fact, the bdd100k results are evaluated on 7 classes, it should be 8, right? This makes me confused. 

Thanks a lot.

**Comment by encounter1997** [comment]
Hi, thanks for your interest. The additional classes are simply not used during training and evaluation. This is similar to DETR's implementation [here](https://github.com/facebookresearch/detr/blob/8a144f83a287f4d3fece4acdf073f387c5af387d/models/detr.py#L313), which sets 91 classes for training on COCO, but only 80 of them are activated.
